# Coding the Perceptron Algorithm

Recall that the perceptron step works as follows. For a point with coordinates (p,q), label y, and prediction given by the equation y_hat = step(w_1x_1 + w_2x_2 + b)

- If the point is correctly classified, do nothing.
- If the point is classified positive, but it has a negative label, subtract αp,αq, and α from w_1, w_2 and b respectively.
- If the point is classified negative, but it has a positive label, add αp, αq, and α to w_1, w_2 and b respectively.

In [101]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

In [102]:
data = np.loadtxt("data.csv", delimiter=",")
X = data[:,:-1]
y = data[:,-1:]

In [103]:
def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

In [104]:
# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    for i in range(len(X)):
        y_hat = prediction(X[i], W, b)
        if y[i] - y_hat == 1: # postive point in the negative area
            W[0] = W[0] + learn_rate*X[i][0]
            W[1] = W[1] + learn_rate*0.1*X[i][1]
            b = b+learn_rate
        elif y[i]-y_hat == -1: # negative point in the positive area
            W[0] = W[0] - learn_rate*X[i][0]
            W[1] = W[1] - learn_rate*X[i][1]
            b = b - learn_rate
    return W, b

In [105]:
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    """
    This function runs the perceptron algorithm repeatedly on the dataset,
    and returns a few of the boundary lines obtained in the iterations,
    for plotting purposes.
    Feel free to play with the learning rate and the num_epochs,
    and see your results plotted below.
    """
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    # Randon weights and bias
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

In [106]:
trainPerceptronAlgorithm(X,y)

[(array([-0.05239463]), array([-2.04919443])),
 (array([1.23772563]), array([-2.90815949])),
 (array([-39.47663703]), array([23.57864461])),
 (array([-11.34158346]), array([6.1013522])),
 (array([-7.48129832]), array([3.75477488])),
 (array([-5.5183233]), array([2.9333658])),
 (array([-4.3269953]), array([2.43485328])),
 (array([-3.65789199]), array([2.17597733])),
 (array([-3.14966347]), array([1.979507])),
 (array([-2.76824493]), array([1.7667891])),
 (array([-2.50479936]), array([1.68904009])),
 (array([-2.24140556]), array([1.53587177])),
 (array([-2.04891848]), array([1.48369712])),
 (array([-1.85685075]), array([1.36731875])),
 (array([-1.70956315]), array([1.33084089])),
 (array([-1.57734918]), array([1.24156358])),
 (array([-1.47250245]), array([1.21765778])),
 (array([-1.36817659]), array([1.14439036])),
 (array([-1.28228903]), array([1.1268416])),
 (array([-1.20318457]), array([1.11067878])),
 (array([-1.12628491]), array([1.05235843])),
 (array([-1.05966358]), array([1.04028